#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Framework
#
VERSION = 0.1
PACKAGE_NAME = AudioToolbox
FRAMEWORK_NAME = AudioToolbox

#
# Resource files
#
AudioToolbox_RESOURCE_FILES = \
Resources/Version \

#
# Header files
#
AudioToolbox_HEADER_FILES = \
AudioToolbox.h \
AudioConverter.h \
AudioFile.h \
AudioFileComponent.h \
AudioFileStream.h \
AudioFormat.h \
AudioQueue.h \
AudioUnitUtilities.h \
AUGraph.h \
AUMIDIController.h \
CAFFile.h \
CodeAudioClock.h \
ExtendedAudioFile.h \
MusicPlayer.h \
AudioServices.h

#
# Class files
#
AudioToolbox_CC_FILES = \
AudioToolbox.cpp \
AudioConverter.cpp \
AudioFile.cpp \
AudioFileComponent.cpp \
AudioFileStream.cpp \
AudioFormat.cpp \
AudioQueue.cpp \
AudioUnitUtilities.cpp \
AUGraph.cpp \
AUMIDIController.cpp \
CAFFile.cpp \
CodeAudioClock.cpp \
ExtendedAudioFile.cpp \
MusicPlayer.cpp \
AudioServices.cpp

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
